### ISSUE TITLE
插件无法被AU扫描识别

### ISSUE THREAD

**Issue by Agnes4m** [zhaohui8969/VST_NetProcess-#2]
我用的是Adobe Audition 2021，选择文件夹后好像扫描不出来插件

**Comment by xiaobaozi233** [comment]
C:\Program Files\Common Files\VST3
你放在这下面试试，我放进去就好了

**Comment by Agnes4m** [comment]
![image](https://user-images.githubusercontent.com/70925546/215301585-dde86a6f-8986-4f57-bf0b-5f2519928a68.png)
我是放这个位置了，但是没有用。。。

**Comment by zhaohui8969** [comment]
比较玄学

**Comment by zhaohui8969** [comment]
试试2.0版本，换了兼容性好的框架
