### ISSUE TITLE
插件在AU中无法调用

### ISSUE THREAD

**Issue by bisonniu** [zhaohui8969/VST_NetProcess-#3]
可以被插件管理器扫描到，可以启用。可以在插件选择中显示名称，但是点击后效果器中并没有添加效果器。
win10  AU2022.0.0.96版本64位
插件默认位置C:\Program Files\Common Files\VST3\NetProcess.vst3
插件版本V1.3 20221023

**Comment by zhaohui8969** [comment]
试试最新的2.0
