### ISSUE TITLE
[Feature] Request iZotope RX10 support

### ISSUE THREAD

**Issue by jsionr** [zhaohui8969/VST_NetProcess-#4]
# Summary
Cannot be supported iZotope RX10 on latest version v3.2, please add it to the support list in the future.

![image](https://user-images.githubusercontent.com/3520241/224355387-65181902-1b2d-40d4-9d65-43e8f82b0ba4.png)

**Comment by zhaohui8969** [comment]
try v3.3 version

**Comment by jsionr** [comment]
> try v3.3 version

maybe u forgot to upload the samplerate.dll file in the release package, I'll try this next time

**Comment by zhaohui8969** [comment]
I remove samplerate.dll from v3.3 vesion

**Comment by jsionr** [comment]
> I remove samplerate.dll from v3.3 vesion

Thanks for your efforts but it still doesn't work, I am turning to Audition and it works fine.
