### ISSUE TITLE
服务器传输异常？

### ISSUE THREAD

**Issue by WelchYang** [zhaohui8969/VST_NetProcess-#8]
![QQ图片20230401193427](https://user-images.githubusercontent.com/33473856/229286370-b6490052-90bd-43c2-8537-87e7623c4bca.png)
家里两台电脑，通过路由器相连。
主机开daw上挂了vst，副机开服务端。现在好像是数据传的过去但是传不回来？
想问问这该怎么解决呀，vst上也有正常显示延迟什么的但就是没声音

**Comment by WelchYang** [comment]
还有就是想问问有推荐的可支持vst网络传输的端吗

**Comment by zhaohui8969** [comment]
这是服务端问题，不是vst问题，服务端报错了
